--FIND TOP 10 HIGHEST REVENUE GENERATING PRODUCTS 
SELECT
	PRODUCT_ID,ROUND(SUM(SALE_PRICE)::NUMERIC,1) AS TOTAL_REVENUE
FROM ORDERS_TABLE
GROUP BY 1
ORDER BY SUM(SALE_PRICE) DESC
LIMIT 10;

--FIND TOP 5 HIGHEST SELLING PRODUCTS IN EACH REGION
WITH CTE AS(
	SELECT 
		REGION,PRODUCT_ID,ROUND(SUM(SALE_PRICE)::NUMERIC,1) AS TOTAL_SALES,
		ROW_NUMBER() OVER (PARTITION BY REGION ORDER BY SUM(SALE_PRICE) DESC) AS RN
	FROM ORDERS_TABLE		
	GROUP BY 1,2
)
SELECT 
	REGION,PRODUCT_ID,TOTAL_SALES,RN AS RANK
FROM CTE
WHERE RN<=5
ORDER BY REGION,RN ASC;


	
--FIND MONTH OVER MONTH GROWTH COMPARISION FOR 2022 AND 2023 SALES EG : JAN 2022 VS JAN 2023
WITH CTE AS
	(SELECT 
	 	EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
	 	EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,
	 	ROUND(SUM(SALE_PRICE)::NUMERIC,1) AS SALES
	FROM ORDERS_TABLE
	GROUP BY MONTH,YEAR
	ORDER BY MONTH,YEAR)
SELECT
	MONTH,
	ROUND(SUM(CASE WHEN YEAR=2022 THEN SALES ELSE 0 END)::NUMERIC,2) AS SALES_2022,
	ROUND(SUM(CASE WHEN YEAR=2023 THEN SALES ELSE 0 END)::NUMERIC,2) AS SALES_2023
FROM CTE
GROUP BY MONTH;



--FOR EACH CATEGORY WHICH MONTH HAD HIGHEST SALES 
WITH CTE AS(
	SELECT CATEGORY,
			EXTRACT(YEAR FROM ORDER_DATE) AS YEAR,
			EXTRACT(MONTH FROM ORDER_DATE) AS MONTH,ROUND(SUM(SALE_PRICE)::NUMERIC,1) AS TOTAL_SALES
	FROM ORDERS_TABLE
	GROUP BY 1,2,3
	ORDER BY 1,2,3),
CTE2 AS(
	SELECT 
		CATEGORY,YEAR,MONTH,TOTAL_SALES,MAX(TOTAL_SALES) OVER (PARTITION BY CATEGORY) AS MAX_SALES 
	FROM CTE
)
SELECT 
	CATEGORY,YEAR,MONTH,TOTAL_SALES
FROM CTE2 
WHERE TOTAL_SALES=MAX_SALES;


--WHICH SUB CATEGORY HAD HIGHEST GROWTH BY PROFIT IN 2023 COMPARE TO 2022
WITH CTE AS(
	SELECT SUB_CATEGORY,EXTRACT(YEAR FROM ORDER_DATE) AS YEAR , SUM(PROFIT) AS TOTAL_PROFIT
	FROM ORDERS_TABLE
	GROUP BY 1,2),
CTE2 AS(
	SELECT 
		SUB_CATEGORY, 
		SUM(CASE WHEN YEAR=2022 THEN TOTAL_PROFIT ELSE 0 END) AS TOTAL_PROFIT_2022,
		SUM(CASE WHEN YEAR=2023 THEN TOTAL_PROFIT ELSE 0 END) AS TOTAL_PROFIT_2023,
		SUM(CASE WHEN YEAR=2023 THEN TOTAL_PROFIT ELSE 0 END)-SUM(CASE WHEN YEAR=2022 THEN TOTAL_PROFIT ELSE 0 END) AS PROFIT_INCREASE
	FROM CTE
	GROUP BY SUB_CATEGORY)
SELECT *,
	CONCAT(ROUND(((PROFIT_INCREASE *100)/TOTAL_PROFIT_2022)::NUMERIC,2),' %') AS GROWTH_PCT 
FROM CTE2 
ORDER BY PROFIT_INCREASE DESC
LIMIT 1;


